# Generated by Django 3.0.7 on 2020-12-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiclecategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_name', models.CharField(max_length=50, null=True)),
                ('describe', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(default='', max_length=40)),
                ('vehicle_number', models.CharField(max_length=12, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('slot_active', models.BooleanField(default=True, null=True)),
                ('valid_time', models.CharField(blank=True, choices=[('2 hours', '2 hours'), ('4 hours', '4 hours'), ('8 hours', '8 hours'), ('12 hours', '12 hours'), ('24 hours', '24 hours')], max_length=20, null=True)),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.Slot')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiclecategory.Category')),
            ],
        ),
    ]
