# Generated by Django 3.0.7 on 2020-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20201209_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default='', max_length=40),
        ),
    ]
