# Generated by Django 3.1.4 on 2020-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20201211_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='vehicle_number',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
